version: "3"
services:
    object_detection:
        build:
            context: .
            dockerfile: Dockerfile
        image: theyseemerollin_artifacts_object_detection:theyseemerollin_object_detection
        ports:
            - "7331:7331"
        environment:
            - QT_X11_NO_MITSHM=1
            - DISPLAY=$DISPLAY
            - NVIDIA_VISIBLE_DEVICES=all
        container_name: ra_object_detection
        # runtime: nvidia
        stdin_open: true
        tty: true
        volumes:
            - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
            - "./rsa:/home/rsa"
            - "./data:/home/data"